/*
 * \file UavCanId.h
 */

#ifndef CAN_ARES_UAVCANID_H_
#define CAN_ARES_UAVCANID_H_

#define ARES_SUBJECT_ID_GNSS_PARAMS				 509
#define ARES_SUBJECT_ID_PHASOR_PARAMS				 508
#define ARES_SUBJECT_ID_CAN_PARAMS				 507
#define ARES_SUBJECT_ID_ADC_PARAMS				 506
#define ARES_SUBJECT_ID_ADC_SYNC				 505
#define ARES_SUBJECT_ID_STORAGE_PARAMS				 504
#define ARES_SUBJECT_ID_STORAGE_CONTROL				 503
#define ARES_SUBJECT_ID_CLOCK_PARAMS				 499
#define ARES_SUBJECT_ID_CLOCK_CONTROL				 502
#define ARES_SUBJECT_ID_FFT_PARAMS				 501
#define ARES_SUBJECT_ID_FFT_CONTROL				 500
#define ARES_SUBJECT_ID_CONSOLE_INPUT				 499
#define ARES_SUBJECT_ID_CONSOLE_CONTROL				 498
#define ARES_SUBJECT_ID_LED_CONTROL				 497
#define ARES_SUBJECT_ID_ACCELEROMETER_CONTROL		 	 496
#define ARES_SUBJECT_ID_RPM_CONTROL				 497

#define ARES_SUBJECT_ID_PHASOR_FIELD				1235
#define ARES_SUBJECT_ID_GNSS_POSITION				1236
#define ARES_SUBJECT_ID_GNSS_RTCM				1237
#define ARES_SUBJECT_ID_WX_WX					1238
#define ARES_SUBJECT_ID_WX_WIND					1239
#define ARES_SUBJECT_ID_PHASOR_PROXY				1240
#define ARES_SUBJECT_ID_FFT_FULL_SPECTRUM			1241
#define ARES_SUBJECT_ID_FFT_INTENSITY				1242
#define ARES_SUBJECT_ID_FFT_BEARING_ANGLES			1243
#define ARES_SUBJECT_ID_FFT_ADC_FRAME				1244
#define ARES_SUBJECT_ID_CONSOLE_OUTPUT				1245

#endif /* CAN_ARES_UAVCANID_H_ */
